# See "erb_filter_extension.rb" for details.

require 'erb'

class Filters::ErbFilter < ::Filters::TextFilter
  description_file File.dirname(__FILE__) + "/../filter_descriptions/erb.html"

  # Radiant pages using the ERB behavior expect something close to
  # ActionView behavior, so include ERB::Util for things like url_encode().

  include ERB::Util

  # ActionView magic; define an empty module within ourselves, which we will
  # use to evaluate a Ruby source code equivalent of the ERB template that is
  # generated by the ERB module, munged to include our instance variables by
  # wrapping the ERB-generated code in an outer function declaration with
  # various local variable definitions.

  module ERBFilterCompiledTemplates
  end

  include ERBFilterCompiledTemplates

  def filter(text)
    # "request()" and "session()" come from a grotty hack which uses a filter
    # patched into ApplicationController by "erb_filter_extension.rb".

    extended_filter(text, {})#{ :request => request(), :session => session() })
  end

  # The extended interface presently expects to have just one extra
  # argument, which is a hash of name/value pairs containing the name
  # of the callers instance variables and their values (or at least,
  # those variables that the caller wishes to expose to this filter).

  def extended_filter(text, *args)
    vars = args[0]

    # We must set the instance variables first. Clearly this is a
    # potentially dangerous operation - we have to hope that the caller
    # does not provide any variable names that match anything we use.
    # Rails' .rhtml mechanism has this problem too.

    vars.each do |key, val|
      instance_variable_set("@#{key}", val)
    end

    # Get a new ERB instance and use an undocumented method, as used by
    # ActionView, to get at the Ruby source equivalent of the template.

    src = ERB.new(text).src

    # We now add code to set the instance variables inside that source.
    # To do this, we wrap the source in a function that takes the hash of
    # variables then self-initialises based on that hash; this is straight
    # out of ActionView too, pretty much.

    locals_code = ''
    locals_keys = vars.keys
    locals_keys.each do |key|
      locals_code << "#{key} = local_variables[:#{key}] if local_variables.has_key?(:#{key})\n"
    end

    code = "def erbfilter_render(local_variables)\n" +
             "#{locals_code}\n"+
             "#{src}\n" +
           "end\n"

    # Evaluate the code within the temporary internal class, thus defining
    # the temporary rendering method.

    ERBFilterCompiledTemplates.module_eval(code)

    # Call that method to return the final result.

    return erbfilter_render(vars)
  end
end
